name: Docker CI/CD

on:
  push:
    branches:
      - test  # Aquí se puede especificar cualquier rama, en este caso 'test'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t create_customer_service .
        docker tag create_customer_service:latest ${{ secrets.DOCKER_USERNAME }}/create_customer_service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/create_customer_service:latest

    - name: Run Docker container
      run: |
        docker run -p 5000:5000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/create_customer_service:latest
